name: Test install

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  install-swift:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: Test Swift toolchain install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install Swift
      uses: ./
      with:
        branch: development
        tag: DEVELOPMENT-SNAPSHOT-2023-05-20-a

    - name: check swift version
      run: swift --version | grep 5.9-dev
      shell: bash

    - name: get macOS smoke test prerequisites
      if: ${{ runner.os == 'macOS' }}
      run: brew install ninja

    - name: Smoke test
      run: cmake -GNinja -S .github/smoke-test -B .cmake-build && cmake --build .cmake-build
